version: '3'
services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=flaskdb
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
